name = input("What is your name: ")
print("Hello ", name)
age = input("How old are you: ")
print("Hello", name, "you're", age, "years old")
year = input("What school year are you in: ")
print("Hello", name, "you're", age, "years old and you're in year" ,year)
